import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";

import { BASE_URL, getCredentials, logIn } from "../services/auth";

const Home: NextPage = () => {
  let [name, setName] = useState("none");
  let [log, setLog] = useState("You Are Not Logged In");
  let [user, setUser] = useState(new LoginUserDto());
  let [cred, setCred] = useState("Enter Your Credentials");

  const option = name === "none" ? "Github" : "Log Out?";

  const link =
    name === "none"
      ? BASE_URL + "oauth2/authorization/github"
      : BASE_URL + "logout";

  const handleChange = (e: any) => {
    setUser({ ...user, [e.target.name]: e.target.value });
    console.log(user);
  };

  const loginUser = () => {
    logIn(user).then(async (res) => {
      if (res.status === 401) {
        const data = await res.json();
        setCred(data);
        return;
      }
      setCred("Congrats!");
      setName(user.username);
    });
  };

  useEffect(() => {
    getCredentials().then((res) => {
      setName(res.data);
      if (name === "none" || res.data === "none") return;
      setLog("You Are Logged In");
    });
  }, [name]);

  return (
    <div>
      <Head>
        <title>Next OAuth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex items-center bg-green-500 text-white font-bold -500 h-20 justify-around ">
        <div>{log}</div>
        <div>{name}</div>
      </div>
      <div className="container  bg-green-600 mx-auto mt-20 py-4 ">
        <div className="flex justify-start rounded-lg flex-col">
          <label htmlFor="usernameid" className="text-white font-bold ml-4">
            Username
          </label>
          <input
            onChange={(e) => handleChange(e)}
            className="mr-20 ml-10 mt-3 py-3 px-2  rounded-lg"
            type="text"
            name="username"
            id="usernameid"
          />
          <label
            htmlFor="passwordid"
            className="mt-5 text-white font-bold ml-4"
          >
            Password
          </label>
          <input
            onChange={(e) => handleChange(e)}
            className="mr-20 ml-10 mt-3 py-3 px-2 mb-5  rounded-lg"
            type="password"
            name="password"
            id="passwordid"
          />
        </div>
        <button
          onClick={() => loginUser()}
          className="ml-7 mt-6 place-self-end bg-blue-600 rounded-lg text-white font-semibold py-2 px-6 hover:bg-blue-700"
        >
          Log In
        </button>
        <div className="bg-yellow-300"></div>
        <div className="ml-4 mt-3 text-white font-bold">{cred}</div>
      </div>

      <a
        className="h-7 rounded-sm shadow-sm bg-gray-700 mx-auto container mt-10 py-20 hover:bg-gray-800 text-white font-bold  justify-center flex"
        target="_blank"
        href={link}
        rel="noreferrer"
      >
        {option}
      </a>
    </div>
  );
};

export class LoginUserDto {
  username!: string;
  password!: string;

  constructor() {}
}

export default Home;
